CodeGames2017.CustomerRatings/CodeGames2017.CustomerRating.Reporting/Controllers/CustomerRatingsController.cs
using CodeGames2017.CustomerRating.Model;
using CodeGames2017.CustomerRating.Reporting.Model;
using CodeGames2017.CustomerRating.Reporting.Models;
using CodeGames2017CustomerRating;
using Microsoft.OData.Client;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CodeGames2017.CustomerRating.Reporting.Controllers
{
    public class CustomerRatingsController : Controller
    {
        private CodeGames2017CustomerRatingContainer _context = 
            new CodeGames2017CustomerRatingContainer(new Uri("http://localhost:28305/odata"));

        // GET: CustomerRatings
        public async Task<ActionResult> Index()
        {
            
            var applications = _context.Applications
                .Execute() as QueryOperationResponse<Application>;

            var viewModel = new ApplicationViewModel
            {
                Applications = applications
            };

            return View(viewModel);
        }

        public async Task<ActionResult> Feature(Guid applicationId)
        {
            var applications = await _context.Applications
                .Expand(a => a.Features)
                .ExecuteAsync() as QueryOperationResponse<Application>;

            var app = applications.FirstOrDefault(x => x.ApplicationId == applicationId);
            var appF = app.Features.ToList();

            

            var viewModel = new FeatureViewModel
            {
                Features = appF
            };


            //foreach (var feature in appFeatures)
            //{
            //    var count = feature.Ratings.Count();
            //    var avg = feature.Ratings.Sum(x=>x.RatingValue) / count;
            //    var one = feature.Ratings.Where(x => x.RatingValue == 1).Count();
            //    var two = feature.Ratings.Where(x => x.RatingValue == 2).Count();
            //    var three = feature.Ratings.Where(x => x.RatingValue == 3).Count();
            //    var four = feature.Ratings.Where(x => x.RatingValue == 4).Count();
            //    var five = feature.Ratings.Where(x => x.RatingValue == 5).Count();
            //    var rptData = new ReportData
            //    {
            //        TotalRatings = count,
            //        AvgRating = avg,
            //        Rating1 = one,
            //        Rating2 = two, 
            //        Rating3 = three, 
            //        Rating4 = four, 
            //        Rating5 = five
            //    };

            //}
           

            //view

            return View(viewModel);
        }

        //public async Task<ActionResult> Details(Guid id)
        //{

        //    var application = await _context.Applications
        //        .ByKey(id)
        //        .GetValueAsync();

        //    var features = _context.Applications.

        //    var viewModel = new ApplicationViewModel
        //    {
        //        ApplicationId = application.ApplicationId,
        //        ApplicationName = application.ApplicationName
        //    };


        //    return View(viewModel);
        //}
    }
}

CodeGames2017.CustomerRatings/CodeGames2017.CustomerRating.Reporting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Customer Ratings Reports</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Customer Ratings Reports", "Index", "CustomerRatings", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Customer Ratings", "Index", "CustomerRatings")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Customer Ratings</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>