CodeGames2017.CustomerRatings/CodeGames2017.CustomerRating.WebSite/Models/RatingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodeGames2017.CustomerRating.WebSite.Models
{
    public class RatingViewModel
    {
        public Guid ApplicationId { get; set; }
        [Display(Name = "Application")]
        public string Application { get; set; }

        public Guid FeatureId { get; set; }
        [Display(Name = "Feature")]
        public string Feature { get; set; }

        [Display(Name="Rating(1-5)")]
        public int RatingValue { get; set; }

        [Display(Name = "Comment")]
        public string Comment { get; set; }

        [Display(Name = "Email")]
        public string RatedBy { get; set; }

        public string ClientCode { get; set; }
    }
}

CodeGames2017.CustomerRatings/CodeGames2017.CustomerRating.WebSite/Controllers/RatingController.cs
using CodeGames2017.CustomerRating.DataAccessLayer;
using CodeGames2017.CustomerRating.Model;
using CodeGames2017.CustomerRating.WebSite.Models;
using CodeGames2017.CustomerRatings.DataService;
using CodeGames2017CustomerRating;
using Microsoft.OData.Client;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CodeGames2017.CustomerRating.WebSite.Controllers
{
    public class RatingController : Controller
    {
        private CodeGames2017CustomerRatingContainer _context =
            new CodeGames2017CustomerRatingContainer(new Uri("http://localhost:28305/odata"));

        private RatingsDbContext _db = new RatingsDbContext();

        // GET: Rating
        public async Task<ActionResult> Index(Guid applicationId, Guid featureId, string clientCode) {
            var application = await _context.Applications
                .ByKey(applicationId)
                .GetValueAsync();

            var applicationFeature = await _context.Features
                .ByKey(featureId)
                .GetValueAsync();

            var viewModel = new RatingViewModel
            {
                ClientCode = clientCode,
                ApplicationId = application.ApplicationId,
                Application = application.ApplicationName,
                FeatureId = applicationFeature.FeatureId,
                Feature = applicationFeature.FeatureName
            };

            return View(viewModel);
        }

        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Index(RatingViewModel model) {
            //var application = await _context.Applications
            //    .ByKey(model.ApplicationId)
            //    .GetValueAsync();

            var feature = await _context.Features
                .ByKey(model.FeatureId)
                .GetValueAsync();

            //var feature = _context.Features
            //    .Expand(r => r.Ratings)
            //    .FirstOrDefault(r => r.FeatureId == model.FeatureId);
                
            //var ratings = await _context.Ratings
            //    .ByKey

                         

            var rating = new RatingAppDomain
            {
                Feature = feature.FeatureId,
                ClientCode = model.ClientCode,
                Comment = model.Comment,
                RatedBy = model.RatedBy,
                RatingValue = model.RatingValue,
                RatingId = Guid.NewGuid()
            };



            //_context.UpdateObject(feature);
            ////_context.AddToRatings(rating);
            //_context.SaveChanges(SaveChangesOptions.ReplaceOnUpdate);


            //var service = new Service();
            //service.AddRating(rating);

            return new HttpStatusCodeResult(200); 
        }
    }
}

CodeGames2017.CustomerRatings/CodeGames2017.CustomerRating.WebSite/Views/Rating/Close.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <script type="text/javascript">
        window.close();
    </script>
</body>
</html>

CodeGames2017.CustomerRatings/CodeGames2017.CustomerRating.WebSite/Views/Rating/Index.cshtml
@using CodeGames2017.CustomerRating.WebSite.Models
@model RatingViewModel

@{
    ViewBag.Title = "Customer Ratings";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Rating", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
    <div class="form-group">
        @Html.LabelFor(m => m.Application, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Application, new { @class = "form-control", @readonly = true })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Feature, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Feature, new { @class = "form-control", @readonly = true })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RatedBy, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RatedBy, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RatingValue, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RatingValue, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Comment, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Comment, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(m => m.ClientCode)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(m => m.ApplicationId)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(m => m.FeatureId)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}